### ISSUE TITLE
Chromecast - Unable to cast when video is already playing.

### ISSUE THREAD

**Issue by thisanimus** [mediaelement/mediaelement-plugins#37] opened 2017-05-02 03:20 UTC
The chromecast plugin is an excellent addition, thanks for your work.  I have noticed two related behaviors:
1) Unable to cast 'on the fly' when video is already playing.
2) Unable to begin from the middle of a video.
Both of these cases results in the grey screen with the little blue chromecast icon, but no video.

For observation purposes:
https://anchored.countrysidebible.org/?lesson=the-inerrancy-preservation-and-translation-of-scripture-part-2&media=video

https://countrysidebible.org/cbcmedia?return=single&mediacode=ja170423a

**Comment by rafa8626** [comment] 2017-05-02 03:23
Thanks for reporting this. I'll take a look at this for sure and keep you posted

**Comment by rafa8626** [comment] 2017-05-02 12:49
@thisanimus I've done some work on the plugin; if you download the master branch of this project and test it, let me know if it worked for you. If not, I'd ask you to give me specific steps in order to reproduce this, please. Thanks

**Comment by rafa8626** [comment] 2017-05-05 10:17
Any updates on this?

**Comment by rafa8626** [comment] 2017-05-07 14:30
Closing this issue since no answer has been posted on a week. If you would like this to be reopened, let us know. Thanks.

----------
Please star us at https://github.com/mediaelement/mediaelement and https://github.com/mediaelement/mediaelement-plugins to continue improving the package and giving it more popularity; also tell your friends/coworkers/etc. to support the project, if you don't mind.It would be greatly appreciated it

**Closed by rafa8626** 2017-05-07 14:30 UTC
Labels: Completed
