### ISSUE TITLE
error building playlist TypeError: Assignment to read-only properties is not allowed in strict mode

### ISSUE THREAD

**Issue by 7huo** [mediaelement/mediaelement-plugins#88] opened 2017-09-03 06:30 UTC
I noticed one issue in playlist plugin.
Edge:
![qq 20170903142231](https://user-images.githubusercontent.com/2534718/30001042-628242c8-90b4-11e7-975f-9d0e1bbc5ad5.png)

**Comment by rafa8626** [comment] 2017-09-05 04:19
Which version of the player are you using?

**Comment by rafa8626** [comment] 2017-09-05 10:52
@7huo Download the master branch and you will see it is fixed now; it was caused by the use of a property that was not the proper one to set the classes of an element. Please star the project to support it. Thanks

**Closed by rafa8626** 2017-09-05 10:52 UTC

**Comment by 7huo** [comment] 2017-09-05 18:26
Thanks,it show now.But playlist item cannot be clicked,

**Comment by rafa8626** [comment] 2017-09-05 19:19
Thanks for pointing this. It should be fixed now. Please download the master branch again and test this, and please star the project to support it.

**Comment by 7huo** [comment] 2017-09-06 08:15
Auto playnext

`diff --git a/dist/playlist/playlist.js b/dist/playlist/playlist.js
index 3767ba3..c3fa504 100644
--- a/dist/playlist/playlist.js
+++ b/dist/playlist/playlist.js
@@ -52,7 +52,7 @@
 		controls.style.zIndex = 5;
 
 		player.endedCallback = function () {
\-			if (player.currentPlaylistItem < player.totalItems) {
\+			if (player.currentPlaylistItem < player.listItems.length) {
 				player.setSrc(player.playlist[++player.currentPlaylistItem]);
 				player.load();
 				player.play();
`

**Comment by rafa8626** [comment] 2017-09-06 10:28
@7huo Thank you very much for helping me with these issues. The fix you mentioned above is now on master branch
