### ISSUE TITLE
choose quality

### ISSUE THREAD

**Issue by jimmywarting** [mediaelement/mediaelement-plugins#33] opened 2017-04-26 21:02 UTC
source choser wasn't really what i was looking for...
it only allows switching source. not changing the quality in a one dash or hls stream that has multiple sources in one

**Comment by rafa8626** [comment] 2017-04-26 21:25
That plugin hasn't been developed yet. #1 reported the desire of having that feature, but I haven't started it. Closing this as considered a duplicate of the ticket mentioned before

**Closed by rafa8626** 2017-04-26 21:25 UTC
